export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  categorySlug: string;
  icon: string;
  gradient: string;
  featured: boolean;
}

export const tools: Tool[] = [
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, paragraphs, and estimate reading time in real time.',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'tabler:letter-case',
    gradient: 'from-emerald-500 to-teal-600',
    featured: true,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    description: 'Format, validate, minify, and beautify JSON data with syntax error detection.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:code',
    gradient: 'from-amber-500 to-orange-600',
    featured: true,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, random passwords with customizable length, uppercase, numbers, and symbols.',
    category: 'Generators',
    categorySlug: 'generator',
    icon: 'tabler:lock',
    gradient: 'from-rose-500 to-pink-600',
    featured: true,
  },
  {
    slug: 'base64',
    name: 'Base64 Encoder & Decoder',
    description: 'Encode text to Base64 or decode Base64 strings back to readable text instantly.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:arrows-exchange',
    gradient: 'from-violet-500 to-purple-600',
    featured: true,
  },
  {
    slug: 'color-converter',
    name: 'Color Converter',
    description: 'Convert colors between HEX, RGB, and HSL formats with live visual preview.',
    category: 'Converters',
    categorySlug: 'converter',
    icon: 'tabler:palette',
    gradient: 'from-sky-500 to-blue-600',
    featured: true,
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder & Decoder',
    description: 'Encode or decode URL strings for safe web transmission using standard percent-encoding.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:link',
    gradient: 'from-indigo-500 to-blue-600',
    featured: false,
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder text with adjustable paragraphs, sentences, or word count.',
    category: 'Generators',
    categorySlug: 'generator',
    icon: 'tabler:file-text',
    gradient: 'from-lime-500 to-green-600',
    featured: false,
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA-256, SHA-512, and SHA-1 hashes from any text using the Web Crypto API.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:hash',
    gradient: 'from-fuchsia-500 to-pink-600',
    featured: false,
  },
  {
    slug: 'text-diff',
    name: 'Text Diff Checker',
    description: 'Compare two blocks of text and highlight line-by-line differences instantly.',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'tabler:git-compare',
    gradient: 'from-cyan-500 to-teal-600',
    featured: false,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with real-time matching, highlighting, and match details.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:regex',
    gradient: 'from-orange-500 to-red-600',
    featured: false,
  },
  {
    slug: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Write Markdown on the left and see the rendered HTML preview on the right in real time.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:markdown',
    gradient: 'from-slate-500 to-gray-700',
    featured: false,
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate RFC 4122 compliant UUID v4 identifiers. Bulk generate up to 100 UUIDs at once.',
    category: 'Generators',
    categorySlug: 'generator',
    icon: 'tabler:fingerprint',
    gradient: 'from-teal-500 to-emerald-600',
    featured: false,
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert between Unix timestamps and human-readable dates. Current timestamp shown live.',
    category: 'Converters',
    categorySlug: 'converter',
    icon: 'tabler:clock',
    gradient: 'from-blue-500 to-indigo-600',
    featured: false,
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    description: 'Convert text between uppercase, lowercase, title case, sentence case, camelCase, and more.',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'tabler:text-caption',
    gradient: 'from-pink-500 to-rose-600',
    featured: false,
  },
  {
    slug: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert numbers between binary, octal, decimal, and hexadecimal bases instantly.',
    category: 'Converters',
    categorySlug: 'converter',
    icon: 'tabler:calculator',
    gradient: 'from-yellow-500 to-amber-600',
    featured: false,
  },
  {
    slug: 'html-entity-encoder',
    name: 'HTML Entity Encoder / Decoder',
    description: 'Encode special characters to HTML entities or decode HTML entities back to readable text.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:brackets',
    gradient: 'from-red-500 to-rose-600',
    featured: false,
  },
  {
    slug: 'text-to-slug',
    name: 'Slug Generator',
    description: 'Convert any text into a clean, SEO-friendly URL slug with custom separators.',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'tabler:link-minus',
    gradient: 'from-stone-500 to-zinc-600',
    featured: false,
  },
  {
    slug: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers within a range. Supports integers, decimals, and bulk generation.',
    category: 'Generators',
    categorySlug: 'generator',
    icon: 'tabler:dice-5',
    gradient: 'from-red-500 to-orange-600',
    featured: false,
  },
  {
    slug: 'css-unit-converter',
    name: 'CSS Unit Converter',
    description: 'Convert between CSS units: px, em, rem, vw, vh, and percentage. With live preview.',
    category: 'Converters',
    categorySlug: 'converter',
    icon: 'tabler:ruler',
    gradient: 'from-purple-500 to-indigo-600',
    featured: false,
  },
  {
    slug: 'text-reverser',
    name: 'Text Reverser',
    description: 'Reverse text character by character, word by word, or line by line instantly.',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'tabler:sort-descending',
    gradient: 'from-teal-500 to-cyan-600',
    featured: false,
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO-friendly HTML meta tags, Open Graph tags, and Twitter Card tags for your website.',
    category: 'SEO Tools',
    categorySlug: 'seo',
    icon: 'tabler:tags',
    gradient: 'from-green-500 to-emerald-600',
    featured: false,
  },
  {
    slug: 'lorem-image-placeholder',
    name: 'Lorem Image Placeholder',
    description: 'Generate placeholder image URLs with custom dimensions for your designs and mockups.',
    category: 'Generators',
    categorySlug: 'generator',
    icon: 'tabler:photo',
    gradient: 'from-pink-500 to-fuchsia-600',
    featured: false,
  },
  {
    slug: 'whitespace-remover',
    name: 'Whitespace Remover',
    description: 'Remove extra spaces, tabs, line breaks, and leading or trailing whitespace from text.',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'tabler:eraser',
    gradient: 'from-orange-500 to-yellow-600',
    featured: false,
  },
  {
    slug: 'word-frequency-counter',
    name: 'Word Frequency Counter',
    description: 'Analyze text and count how often each word appears. Identify the most common words instantly.',
    category: 'Text Tools',
    categorySlug: 'text',
    icon: 'tabler:chart-bar',
    gradient: 'from-blue-500 to-cyan-600',
    featured: false,
  },
  {
    slug: 'string-escape',
    name: 'String Escape / Unescape',
    description: 'Escape special characters for JSON, JavaScript, HTML, and CSV. Or unescape them back.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:shield-check',
    gradient: 'from-slate-500 to-gray-700',
    featured: false,
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, email, phone numbers, and WiFi credentials. Customize size and colors, download as PNG.',
    category: 'Generators',
    categorySlug: 'generator',
    icon: 'tabler:qrcode',
    gradient: 'from-indigo-500 to-violet-600',
    featured: true,
  },
    {
    slug: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description: 'Convert JSON arrays to CSV format. Flatten nested objects, handle arrays, and download as a CSV file.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:file-type-csv',
    gradient: 'from-teal-500 to-cyan-600',
    featured: false,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens. View header, payload, claims, expiration, and signature.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:key',
    gradient: 'from-amber-500 to-orange-600',
    featured: false,
  },
  {
    slug: 'cron-expression-generator',
    name: 'Cron Expression Generator',
    description: 'Build and understand cron expressions visually. Set schedules with presets, see next run times, and copy expressions.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:clock-code',
    gradient: 'from-emerald-500 to-teal-600',
    featured: false,
  },
  {
    slug: 'json-to-yaml',
    name: 'JSON to YAML Converter',
    description: 'Convert between JSON and YAML formats instantly. Bidirectional conversion with copy and download support.',
    category: 'Developer Tools',
    categorySlug: 'developer',
    icon: 'tabler:arrows-left-right',
    gradient: 'from-rose-500 to-pink-600',
    featured: false,
  },

];

export const categories = [
  { name: 'Text Tools', slug: 'text', description: 'Analyze, compare, and transform text content.' },
  { name: 'Developer Tools', slug: 'developer', description: 'Essential utilities for coding and debugging.' },
  { name: 'Generators', slug: 'generator', description: 'Generate random data, passwords, and placeholder content.' },
  { name: 'Converters', slug: 'converter', description: 'Convert between different data formats and number bases.' },
  { name: 'SEO Tools', slug: 'seo', description: 'Optimize your website for search engines.' },
];

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.categorySlug === categorySlug);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((t) => t.featured);
}
